import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

import { TRPCReactProvider } from "~/trpc/react";
import { Navigation } from "~/components/navigation";
import { ThemeProvider } from "~/components/theme-provider";
import { auth } from "~/server/auth";
import { WebSocketProvider } from "../components/providers/websocket-provider";
import { User, type Session } from "@prisma/client";
export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  const session2 = await auth();
  const session1: unknown = session2;
  const session = session1 as Session & User
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body className="h-full">
        <TRPCReactProvider>
         <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <WebSocketProvider token={session?.sessionToken}>
              <div className="flex p-0 min-h-screen">
                {session2?.user && <Navigation />}
                <main className="flex-1 w-full border-zinc-400 dark:border-zinc-700 border-2">
                  {children}
                </main>
              </div>
            </WebSocketProvider>
          </ThemeProvider>
        </TRPCReactProvider>
      </body>
    </html>
  );
}